"""
Use Hugging Face's `trl` library, it is currently the hottest technique for Preference Alignment.
"""

from trl import DPOTrainer
from transformers import AutoModelForCausalLM, AutoTokenizer
from datasets import Dataset

def train():
    # 1. load base model (e.g., Llama-3-8B or Mistral-7B)
    model = AutoModelForCausalLM.from_pretrained("meta-llama/Meta-Llama-3-8B-Instruct")
    tokenizer = AutoTokenizer.from_pretrained("meta-llama/Meta-Llama-3-8B-Instruct")
    tokenizer.pad_token = tokenizer.eos_token

    # 2. Preparing the Preference Dataset Generated by the RLAIF Judge
    # format: {"prompt": str, "chosen": str, "rejected": str}
    dataset = Dataset.from_json("data/preference_pairs.json")

    # 3. config DPO trainer
    dpo_trainer = DPOTrainer(
        model,
        args=training_args, # ignore detailed paras
        beta=0.1,           # KL penality para
        train_dataset=dataset,
        tokenizer=tokenizer,
    )

    # 4. start training
    dpo_trainer.train()